//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cluster
    {
        public int ClusterID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> BlockID { get; set; }
        public Nullable<int> DistrictCode { get; set; }
        public string ClusterName { get; set; }
        public string AlternateClusterName { get; set; }
        public Nullable<int> ClusterCode { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual District District { get; set; }
    }
}
