//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class schoolInfo
    {
        public int schoolInfoID { get; set; }
        public string STATE_NAME { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string DISTRICT_ID { get; set; }
        public string SCHOOL_AREA { get; set; }
        public string SCHOOL_CATEGORY_NAME { get; set; }
        public string SCHOOL_MEDIUM { get; set; }
        public string STATE_ID { get; set; }
        public string DISTRICT_NAME { get; set; }
        public string BRC_NAME { get; set; }
        public string CRC_NAME { get; set; }
        public string MAX_STANDARD { get; set; }
        public string SCHOOL_CATEGORY { get; set; }
        public string EDUCATION_LEVEL_NAME { get; set; }
        public string SCHOOL_ADDRESS { get; set; }
        public string BRC_ID { get; set; }
        public string EDUCATION_LEVEL { get; set; }
        public string MIN_STANDARD { get; set; }
        public string SCHOOL_MEDIUM_NAME { get; set; }
        public string SCHOOL_AREA_NAME { get; set; }
        public string SCHOOL_ID { get; set; }
        public string DIVISION_ID { get; set; }
        public string DIVISION_NAME { get; set; }
        public string CRC_ID { get; set; }
        public string SCHOOL_MANAGEMENT_NAME { get; set; }
        public string SCHOOL_MANAGEMENT { get; set; }
    }
}
