//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolData
    {
        public int id { get; set; }
        public string SchoolCode { get; set; }
        public string SchoolName { get; set; }
        public string District { get; set; }
        public string Block { get; set; }
        public string Cluster { get; set; }
        public string Status { get; set; }
    }
}
