//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STMSEntities : DbContext
    {
        public STMSEntities()
            : base("name=STMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Block> Blocks { get; set; }
        public virtual DbSet<Cluster> Clusters { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<SchoolData> SchoolDatas { get; set; }
        public virtual DbSet<schoolInfo> schoolInfoes { get; set; }
    }
}
